//Auth Action
export const AUTH_ACTION = 'AUTH_ACTION'
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS'
export const AUTH_ACTION_FAIL = 'AUTH_ACTION_FAIL'

//Register Action
export const REGISTER_ACTION = 'REGISTER_ACTION'
export const REGISTER_ACTION_SUCCESS = 'REGISTER_ACTION_SUCCESS'
export const REGISTER_ACTION_FAIL = 'REGISTER_ACTION_FAIL'