//Auth Action
export const AUTH_ACTION = 'AUTH_ACTION'
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS'
export const AUTH_ACTION_FAIL = 'AUTH_ACTION_FAIL'

//Register Action
export const REGISTER_ACTION = 'REGISTER_ACTION'
export const REGISTER_ACTION_SUCCESS = 'REGISTER_ACTION_SUCCESS'
export const REGISTER_ACTION_FAIL = 'REGISTER_ACTION_FAIL'

//Post Action
export const POST_ACTION = 'POST_ACTION'
export const POST_ACTION_SUCCESS = 'POST_ACTION_SUCCESS'
export const POST_ACTION_FAIL = 'POST_ACTION_FAIL'

//GetPost Action
export const GET_POST_ACTION = 'GET_POST_ACTION'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAIL = 'GET_POST_FAIL'